name: Build Pico UF2

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Important if you include SDK as submodule

      - name: Install Picotool Dependencies
        run: 
          sudo apt-get update
          sudo apt-get install -y libusb-1.0-0-dev pkg-config

      - name: Build Pico Project
        id: build
        uses: samyarsadat/Pico-Build-Action@v1
        with:
          source_dir: "src"
          # Add the FETCH variable here so the action's internal CMake sees it!
          cmake_args: "-DCMAKE_BUILD_TYPE=Release -DPICO_SDK_FETCH_FROM_GIT=ON"
          
      - name: Upload UF2 artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: ${{ steps.build.outputs.output_dir }}/**/*.uf2
          retention-days: 30
